# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sammy/SU-MikkelLNC/SU-Opgave-Mikkel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sammy/SU-MikkelLNC/build-SU-Opgave-Mikkel-Desktop-Debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sammy/SU-MikkelLNC/build-SU-Opgave-Mikkel-Desktop-Debug/CMakeFiles /home/sammy/SU-MikkelLNC/build-SU-Opgave-Mikkel-Desktop-Debug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sammy/SU-MikkelLNC/build-SU-Opgave-Mikkel-Desktop-Debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SU-Opgave-Mikkel

# Build rule for target.
SU-Opgave-Mikkel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SU-Opgave-Mikkel
.PHONY : SU-Opgave-Mikkel

# fast build rule for target.
SU-Opgave-Mikkel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/build
.PHONY : SU-Opgave-Mikkel/fast

#=============================================================================
# Target rules for targets named SU-Opgave-Mikkel_autogen

# Build rule for target.
SU-Opgave-Mikkel_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SU-Opgave-Mikkel_autogen
.PHONY : SU-Opgave-Mikkel_autogen

# fast build rule for target.
SU-Opgave-Mikkel_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel_autogen.dir/build.make CMakeFiles/SU-Opgave-Mikkel_autogen.dir/build
.PHONY : SU-Opgave-Mikkel_autogen/fast

Character.o: Character.cpp.o
.PHONY : Character.o

# target to build an object file
Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Character.cpp.o
.PHONY : Character.cpp.o

Character.i: Character.cpp.i
.PHONY : Character.i

# target to preprocess a source file
Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Character.cpp.i
.PHONY : Character.cpp.i

Character.s: Character.cpp.s
.PHONY : Character.s

# target to generate assembly for a file
Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Character.cpp.s
.PHONY : Character.cpp.s

Enemy.o: Enemy.cpp.o
.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i
.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s
.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

Hero.o: Hero.cpp.o
.PHONY : Hero.o

# target to build an object file
Hero.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Hero.cpp.o
.PHONY : Hero.cpp.o

Hero.i: Hero.cpp.i
.PHONY : Hero.i

# target to preprocess a source file
Hero.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Hero.cpp.i
.PHONY : Hero.cpp.i

Hero.s: Hero.cpp.s
.PHONY : Hero.s

# target to generate assembly for a file
Hero.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Hero.cpp.s
.PHONY : Hero.cpp.s

Magic.o: Magic.cpp.o
.PHONY : Magic.o

# target to build an object file
Magic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Magic.cpp.o
.PHONY : Magic.cpp.o

Magic.i: Magic.cpp.i
.PHONY : Magic.i

# target to preprocess a source file
Magic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Magic.cpp.i
.PHONY : Magic.cpp.i

Magic.s: Magic.cpp.s
.PHONY : Magic.s

# target to generate assembly for a file
Magic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Magic.cpp.s
.PHONY : Magic.cpp.s

Manager.o: Manager.cpp.o
.PHONY : Manager.o

# target to build an object file
Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Manager.cpp.o
.PHONY : Manager.cpp.o

Manager.i: Manager.cpp.i
.PHONY : Manager.i

# target to preprocess a source file
Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Manager.cpp.i
.PHONY : Manager.cpp.i

Manager.s: Manager.cpp.s
.PHONY : Manager.s

# target to generate assembly for a file
Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/Manager.cpp.s
.PHONY : Manager.cpp.s

SU-Opgave-Mikkel_autogen/mocs_compilation.o: SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.o
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.o

# target to build an object file
SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.o
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.o

SU-Opgave-Mikkel_autogen/mocs_compilation.i: SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.i
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.i

# target to preprocess a source file
SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.i
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.i

SU-Opgave-Mikkel_autogen/mocs_compilation.s: SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.s
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.s

# target to generate assembly for a file
SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.s
.PHONY : SU-Opgave-Mikkel_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SU-Opgave-Mikkel.dir/build.make CMakeFiles/SU-Opgave-Mikkel.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SU-Opgave-Mikkel_autogen"
	@echo "... SU-Opgave-Mikkel"
	@echo "... Character.o"
	@echo "... Character.i"
	@echo "... Character.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... Hero.o"
	@echo "... Hero.i"
	@echo "... Hero.s"
	@echo "... Magic.o"
	@echo "... Magic.i"
	@echo "... Magic.s"
	@echo "... Manager.o"
	@echo "... Manager.i"
	@echo "... Manager.s"
	@echo "... SU-Opgave-Mikkel_autogen/mocs_compilation.o"
	@echo "... SU-Opgave-Mikkel_autogen/mocs_compilation.i"
	@echo "... SU-Opgave-Mikkel_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

